import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.116.0";
const norm=(s:any)=>String(s||"").normalize("NFKD").toLowerCase().replace(/\b(fc|cf|afc|sc|club|football|women|w)\b/g,"").replace(/[^a-z0-9]+/g,"");
const sim=(a:string,b:string)=>{a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .9;let same=0;for(const c of new Set(a))if(b.includes(c))same++;return same/Math.max(new Set(a).size,new Set(b).size)};
function key(){const x=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(x)return x;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}")?.default||""}catch{return ""}}
async function json(u:string){const r=await fetch(u,{headers:{Accept:"application/json","User-Agent":"Mozilla/5.0 FastTracker/2.0"},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`http_${r.status}`);return r.json()}
function entries(side:any){if(Array.isArray(side))return side;if(Array.isArray(side?.players))return side.players;return []}
function starterFlag(x:any):boolean|null{if(typeof x?.substitute==='boolean')return !x.substitute;if(typeof x?.starter==='boolean')return x.starter;if(typeof x?.isSubstitute==='boolean')return !x.isSubstitute;return null}
Deno.serve(async()=>{const su=Deno.env.get("SUPABASE_URL")||"",sk=key();if(!su||!sk)return Response.json({ok:false,error:"config"},{status:500});const db=createClient(su,sk,{auth:{persistSession:false}});const fixtures=await db.from("canonical_fixture_current").select("hkjc_event_id:match_id,kickoff_hkt,home_en,away_en,home_zh,away_zh").gte("kickoff_hkt",new Date(Date.now()-2*3600000).toISOString()).lte("kickoff_hkt",new Date(Date.now()+48*3600000).toISOString()).order("kickoff_hkt");if(fixtures.error)throw fixtures.error;const events:any[]=[];for(let d=0;d<3;d++){const dt=new Date(Date.now()+8*3600000+d*86400000).toISOString().slice(0,10);try{const p=await json(`https://www.sofascore.com/api/v1/sport/football/scheduled-events/${dt}`);events.push(...(p.events||[]))}catch{}}
let matched=0,withLineup=0,written=0;const diagnostics:any[]=[];for(const h of fixtures.data||[]){const kt=new Date(h.kickoff_hkt).getTime();let best:any=null;for(const e of events){const et=Number(e.startTimestamp||0)*1000;if(!et||Math.abs(et-kt)>45*60000)continue;const hs=sim(h.home_en||h.home_zh,e.homeTeam?.name),as=sim(h.away_en||h.away_zh,e.awayTeam?.name);const score=(hs+as)/2;if(hs>=.85&&as>=.85&&score>=.88&&(!best||score>best.score))best={e,score,hs,as}}
if(!best){diagnostics.push({id:h.hkjc_event_id,status:"no_match"});continue}matched++;let lp:any;try{lp=await json(`https://www.sofascore.com/api/v1/event/${best.e.id}/lineups`)}catch{diagnostics.push({id:h.hkjc_event_id,sofa:best.e.id,status:"no_lineup"});continue}const home=entries(lp.home||lp.homePlayers||lp.homeTeam),away=entries(lp.away||lp.awayPlayers||lp.awayTeam);const hs=home.filter((x:any)=>starterFlag(x)===true),as=away.filter((x:any)=>starterFlag(x)===true);if(hs.length!==11||as.length!==11){diagnostics.push({id:h.hkjc_event_id,sofa:best.e.id,status:"fail_closed_starter_count",home_starters:hs.length,away_starters:as.length,home_rows:home.length,away_rows:away.length,match_score:best.score,home_similarity:best.hs,away_similarity:best.as});continue}withLineup++;const confirmed=Boolean(lp.confirmed||lp.isConfirmed||lp.lineupsConfirmed);for(const [side,list] of [["H",home],["A",away]] as any[]){for(const x of list){const sf=starterFlag(x);if(sf===null)continue;const p=x.player||x;if(!p?.name)continue;const pkey=p.id?`SOFA:${p.id}`:`SOFAN:${norm(p.name)}`;await db.from("phase2_players").upsert({player_key:pkey,canonical_name:p.name,position:p.position||x.position||null,source_ids:{sofascore:p.id||null},source_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"player_key"});const row:any={hkjc_event_id:h.hkjc_event_id,team_side:side,player_key:pkey,player_name:p.name,role:p.position||x.position||null,starter:sf,formation_slot:x.formationSlot||x.grid||x.position||p.position||null,shirt_number:x.shirtNumber??x.jerseyNumber??p.jerseyNumber??null,confirmed,confidence:confirmed?.99:Math.max(.75,Math.min(.9,best.score)),source_name:"SOFASCORE",source_url:`https://www.sofascore.com/event/${best.e.id}`,source_updated_at:new Date().toISOString(),fetched_at:new Date().toISOString(),raw:{sofascore_event_id:best.e.id,match_score:best.score,home_similarity:best.hs,away_similarity:best.as,classification:confirmed?"FACT":"PREDICTED",entry:x}};const ex=await db.from("phase2_match_lineup_evidence").select("id").eq("hkjc_event_id",h.hkjc_event_id).eq("team_side",side).eq("player_key",pkey).eq("source_name","SOFASCORE").maybeSingle();const wr=ex.data?await db.from("phase2_match_lineup_evidence").update(row).eq("id",ex.data.id):await db.from("phase2_match_lineup_evidence").insert(row);if(!wr.error)written++}}
diagnostics.push({id:h.hkjc_event_id,sofa:best.e.id,status:"written",home:home.length,away:away.length,home_starters:hs.length,away_starters:as.length,confirmed,score:best.score,home_similarity:best.hs,away_similarity:best.as})}
return Response.json({ok:events.length>0,status:events.length>0?"OK":"UPSTREAM_UNAVAILABLE",fixtures:(fixtures.data||[]).length,sofaEvents:events.length,matched,withLineup,written,diagnostics:diagnostics.slice(0,30)})});