-- Collapse correlated internal model methods into one evidence family for Phase 4 value consensus.
-- Dixon-Coles and Pi are generated by the same imported football-data/penaltyblog pipeline,
-- so they must not count as two independent sources. Forebet remains a separate family.
-- Recovery: restore the previous refresh_model_consensus() definition from the preceding
-- migration/repository revision and run select phase4.refresh_core(); no stored source data is changed.

create or replace function phase4.refresh_model_consensus()
returns integer
language plpgsql
set search_path to 'phase4', 'public', 'pg_temp'
as $function$
declare n integer;
begin
  delete from phase4.model_consensus_current;

  insert into phase4.model_consensus_current(
    match_id,market_key,selection_key,model_prob,source_count,source_probs,calculated_at
  )
  with b as (
    select
      m.match_id,
      p.model_source,
      p.dc_prob_home,p.dc_prob_draw,p.dc_prob_away,
      p.pi_prob_home,p.pi_prob_draw,p.pi_prob_away,
      f.prob_home,f.prob_draw,f.prob_away,
      nullif(coalesce(p.dc_prob_home,0)+coalesce(p.dc_prob_draw,0)+coalesce(p.dc_prob_away,0),0) as dc_sum,
      nullif(coalesce(p.pi_prob_home,0)+coalesce(p.pi_prob_draw,0)+coalesce(p.pi_prob_away,0),0) as pi_sum,
      nullif(coalesce(f.prob_home,0)+coalesce(f.prob_draw,0)+coalesce(f.prob_away,0),0) as fb_sum
    from public.canonical_fixture_current m
    left join public.model_prediction_current p using(match_id)
    left join public.forebet_prediction_current f using(match_id)
    where m.kickoff_hkt>=now()-interval '6 hours'
      and m.kickoff_hkt<now()+interval '72 hours'
  ),
  methods as (
    select match_id,model_source,'HOME'::text selection_key,
      case when dc_sum is not null and dc_prob_home is not null then dc_prob_home/dc_sum end dc_p,
      case when pi_sum is not null and pi_prob_home is not null then pi_prob_home/pi_sum end pi_p,
      case when fb_sum is not null and prob_home is not null then prob_home/fb_sum end fb_p
    from b
    union all
    select match_id,model_source,'DRAW',
      case when dc_sum is not null and dc_prob_draw is not null then dc_prob_draw/dc_sum end,
      case when pi_sum is not null and pi_prob_draw is not null then pi_prob_draw/pi_sum end,
      case when fb_sum is not null and prob_draw is not null then prob_draw/fb_sum end
    from b
    union all
    select match_id,model_source,'AWAY',
      case when dc_sum is not null and dc_prob_away is not null then dc_prob_away/dc_sum end,
      case when pi_sum is not null and pi_prob_away is not null then pi_prob_away/pi_sum end,
      case when fb_sum is not null and prob_away is not null then prob_away/fb_sum end
    from b
  ),
  families as (
    select *,
      case
        when dc_p is not null and pi_p is not null then (dc_p+pi_p)/2.0
        else coalesce(dc_p,pi_p)
      end as internal_p
    from methods
  ),
  counted as (
    select *,
      ((internal_p is not null)::int + (fb_p is not null)::int) as nsrc
    from families
  )
  select
    match_id,'HAD_1X2',selection_key,
    (coalesce(internal_p,0)+coalesce(fb_p,0))/nsrc,
    nsrc,
    jsonb_strip_nulls(jsonb_build_object(
      'internal',internal_p,
      'forebet',fb_p,
      'lineage',jsonb_strip_nulls(jsonb_build_object(
        'internal_model_source',model_source,
        'internal_methods',case
          when dc_p is not null and pi_p is not null then jsonb_build_array('dixon_coles','pi')
          when dc_p is not null then jsonb_build_array('dixon_coles')
          when pi_p is not null then jsonb_build_array('pi')
          else null
        end,
        'independent_families',nsrc
      ))
    )),
    now()
  from counted
  where nsrc>0;

  get diagnostics n=row_count;
  return n;
end
$function$;

select phase4.refresh_core();
